export default [
  {
    title: "Ouvindo",
    station: "Antena1",
    radioName: 'antena1',
    logo: '/logo/antena1.png',
    file: "https://stream.antena1.com.br/stream3",
  },
  {
    title: "Ouvindo",
    station: ".977 Today's Hits",
    radioName: '977',
    logo: '/logo/977.png',
    file: "https://playerservices.streamtheworld.com/api/livestream-redirect/977_HITSAAC_SC",
  },
  {
    title: "Ouvindo",
    station: "Alvorada",
    radioName: 'alvorada',
    logo: '/logo/alvorada.png',
    file:"https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO_ALVORADAAAC.aac",
  },
  {
    title: "Ouvindo",
    station: "Jovem Pan BH",
    radioName: 'jpbh',
    logo: '/logo/jpbh.png',
    file:"http://8a3c.live.upx.net.br:8036/stream.mp3",
  },
  {
    title: "Ouvindo",
    station: "Jovem Pan SP",
    radioName: 'jpsp',
    logo: '/logo/jpsp.png',
    file:"https://playerservices.streamtheworld.com/api/livestream-redirect/JP_SP_FMAAC.aac",
  },
  {
    title: "Ouvindo",
    station: "98 Live",
    radioName: '98live',
    logo: '/logo/98live.png',
    file:"https://9554.brasilstream.com.br/stream",
  },
  {
    title: "Ouvindo",
    station: "MIX",
    radioName: 'mix',
    logo: '/logo/mix.png',
    file:"https://playerservices.streamtheworld.com/api/livestream-redirect/MIXFM_SAOPAULOAAC.aac",
  },
  {
    title: "Ouvindo",
    station: "BH FM",
    radioName: 'bhfm',
    logo: '/logo/bhfm.png',
    file:"https://medias.sgr.globo.com/hls/aBHFM/aBHFM.m3u8",
  },
  {
    title: "Ouvindo",
    station: "89 a Radio Rock",
    radioName: '89',
    logo: '/logo/89.png',
    file:"http://13693.live.streamtheworld.com:80/RADIO_89FM_ADP_SC",
  },
  {
    title: "Ouvindo",
    station: "CDL FM",
    radioName: 'cdl',
    logo: '/logo/cdl.png',
    file:"http://9595.brasilstream.com.br/stream",
  },
  {
    title: "Ouvindo",
    station: "CLUBE FM",
    radioName: 'clube',
    logo: '/logo/clube.png',
    file:"https://ice.fabricahost.com.br/clubefmbh",
  },
];